include:
  - project: 'acquiring/devops/pipelines'
    ref: master
    file: '.cms-github.yml'

variables:
  APP_NAME: ecom-cms-bitrix
  APPSEC_TEAM_ID: 47

push:
  script:
    - git config --global user.email $OPEN_SOURCE_GITHUB_EMAIL
    - git config --global user.name $OPEN_SOURCE_GITHUB_LOGIN
    - git rm --cached --ignore-unmatch .gitlab-ci.yml .gitignore meta-info.yaml
    - 'git commit -m "ci: exclude internal files from public repo"'
    - git push https://$OPEN_SOURCE_GITHUB_LOGIN:$OPEN_SOURCE_GITHUB_TOKEN@github.com/Raiffeisen-DGTL/$APP_NAME.git HEAD:main --force
